name: Check Verified Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  verify-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history

      - name: Check Verified Commits
        run: |
          UNVERIFIED_COMMITS=$(git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%h %G?" | grep -v "G$" || true)
          
          if [[ -n "$UNVERIFIED_COMMITS" ]]; then
            echo "❌ Unverified commits detected:"
            echo "Please try and verify your commits"
            echo "$UNVERIFIED_COMMITS"
            exit 1
          else
            echo "✅ All commits are verified."
            echo "We will get back to you as fast as possible ✨"
          fi
