name: Check Verified Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  verify-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history

      - name: Check Verified Commits
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          UNVERIFIED_COMMITS=$(gh api --paginate repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits --jq '.[] | select(.commit.verification.verified == false) | .sha')
          
          if [[ -n "$UNVERIFIED_COMMITS" ]]; then
            echo "❌ Unverified commits detected in this Pull Request:"
            echo "$UNVERIFIED_COMMITS"
            echo "Please ensure all commits are signed and verified."
            exit 1
          else
            echo "✅ All commits in this PR are verified."
            echo "We will get back to you as fast as possible ✨"
          fi